apiVersion: v1
kind: Service
metadata:
  name: wog-postgres
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.postgres.servicePort }}
      targetPort: 5432
  selector:
    app: wog-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wog-postgres-pvc
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wog-postgres
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
spec:
  selector:
    matchLabels: { app: wog-postgres }
  serviceName: wog-postgres
  replicas: 1
  template:
    metadata:
      labels: { app: wog-postgres }
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: wog-db-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
              memory: {{ .Values.postgres.resources.requests.memory | quote }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wog-postgres-pvc
