name: Python tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: api/python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: api/python/requirements-ci.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run tests
        run: pytest -q
